import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { Nav } from '@/features';
import './globals.css';

const poppins = Poppins({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap', // prevent "flash of invisible text" (FOIT)
  variable: '--font-poppins' // for use with Tailwind CSS through a CSS variable
});

// TODO: meta
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <header className="px-2">
          <Nav profile="aga" />
        </header>
        <div className="h-[calc(100vh-64px)]">{children}</div>
      </body>
    </html>
  );
}
